# Generated by Django 3.2.19 on 2023-05-14 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_auto_20230509_0902"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredientrecipe",
            old_name="quantity",
            new_name="amount",
        ),
    ]
